# Generated by Django 3.2 on 2021-06-21 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210612_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='main',
        ),
        migrations.RemoveField(
            model_name='post',
            name='reply_to',
        ),
    ]
